In [2]:
# note : install numpy first then do something here

In [3]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,4))

In [5]:
arr

array([[6, 8, 8, 8],
       [2, 1, 9, 6],
       [5, 1, 1, 2]])

In [6]:
arr.reshape(6,2)

array([[6, 8],
       [8, 8],
       [2, 1],
       [9, 6],
       [5, 1],
       [1, 2]])

In [7]:
arr.reshape(2,6)

array([[6, 8, 8, 8, 2, 1],
       [9, 6, 5, 1, 1, 2]])

In [8]:
# arr.reshape(2,7)  2 X 7 = 14 , but there are only 12 elemensts so you will get error

In [9]:
arr.T # transpose

array([[6, 2, 5],
       [8, 1, 1],
       [8, 9, 1],
       [8, 6, 2]])

In [12]:
arr.flatten() # converts 2d array to  1d array

array([6, 8, 8, 8, 2, 1, 9, 6, 5, 1, 1, 2])

In [13]:
arr1 = np.array([1,2,3,3,4])

In [14]:
arr1.ndim # dimensions

1

In [15]:
np.expand_dims(arr1,axis=1) # convert fom 1 to 2 dimensions across axis=1 which means by column

array([[1],
       [2],
       [3],
       [3],
       [4]])

In [17]:
np.expand_dims(arr1,axis=0)# 2 dimensional array

array([[1, 2, 3, 3, 4]])

In [18]:
np.squeeze(arr) # 

array([[6, 8, 8, 8],
       [2, 1, 9, 6],
       [5, 1, 1, 2]])

In [19]:
data = np.array([[1],[2],[3]])

In [20]:
data

array([[1],
       [2],
       [3]])

In [23]:
np.squeeze(data) # squeeze the data, when there are single elements inside every list

array([1, 2, 3])

In [24]:
arr1

array([1, 2, 3, 3, 4])

In [26]:
np.repeat(arr1,3) # repeat elements 3 times

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 3, 3, 4, 4, 4])

In [28]:
np.roll(arr1,2) # rolling data every data will be shifted to 2 places

array([3, 4, 1, 2, 3])

In [29]:
arr1

array([1, 2, 3, 3, 4])

In [31]:
np.diag(arr1)# creates 2d array and keeps data in diagonal 

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [32]:
# numpy binary operations

In [33]:
arr1 = np.random.randint(1,10,(3,4))

In [34]:
arr2 = np.random.randint(1,10,(3,4))

In [35]:
# lets do binary operations 

In [36]:
arr1 + arr2

array([[11,  9, 10,  4],
       [ 9, 11, 13, 13],
       [ 9,  4,  9, 15]])

In [37]:
arr1 * arr2

array([[24, 18, 21,  3],
       [14, 18, 36, 36],
       [14,  4, 14, 56]])

In [38]:
arr1 / arr2

array([[2.66666667, 2.        , 2.33333333, 3.        ],
       [3.5       , 0.22222222, 2.25      , 2.25      ],
       [0.28571429, 1.        , 0.28571429, 1.14285714]])

In [39]:
arr1 - arr2

array([[ 5,  3,  4,  2],
       [ 5, -7,  5,  5],
       [-5,  0, -5,  1]])

In [40]:
arr%arr2

array([[0, 2, 2, 0],
       [0, 1, 1, 2],
       [5, 1, 1, 2]])

In [41]:
arr**arr2

array([[  216,   512,   512,     8],
       [    4,     1,  6561,  1296],
       [78125,     1,     1,   128]])

In [42]:
-arr2

array([[-3, -3, -3, -1],
       [-2, -9, -4, -4],
       [-7, -2, -7, -7]])

In [43]:
~arr2

array([[ -4,  -4,  -4,  -2],
       [ -3, -10,  -5,  -5],
       [ -8,  -3,  -8,  -8]])

In [44]:
arr | arr2

array([[ 7, 11, 11,  9],
       [ 2,  9, 13,  6],
       [ 7,  3,  7,  7]])

In [45]:
arr1 & arr2

array([[0, 2, 3, 1],
       [2, 0, 0, 0],
       [2, 2, 2, 0]])

In [46]:
arr>arr2

array([[ True,  True,  True,  True],
       [False, False,  True,  True],
       [False, False, False, False]])

In [47]:
arr1 <= arr2

array([[False, False, False, False],
       [False,  True, False, False],
       [ True,  True,  True, False]])

In [48]:
# numpy string function

In [52]:
arr = np.array(['faisal','sudh'])

In [53]:
# convert to uppercase

In [54]:
np.char.upper(arr)

array(['FAISAL', 'SUDH'], dtype='<U6')

In [55]:
arr.dtype

dtype('<U6')

In [56]:
np.char.title(arr)

array(['Faisal', 'Sudh'], dtype='<U6')

In [58]:
np.char.capitalize(arr)

array(['Faisal', 'Sudh'], dtype='<U6')

In [59]:
# math function s

In [60]:
arr1

array([[8, 6, 7, 3],
       [7, 2, 9, 9],
       [2, 2, 2, 8]])

In [61]:
# sin function 

In [62]:
np.sin(arr1)

array([[ 0.98935825, -0.2794155 ,  0.6569866 ,  0.14112001],
       [ 0.6569866 ,  0.90929743,  0.41211849,  0.41211849],
       [ 0.90929743,  0.90929743,  0.90929743,  0.98935825]])

In [63]:
np.cos(arr1)

array([[-0.14550003,  0.96017029,  0.75390225, -0.9899925 ],
       [ 0.75390225, -0.41614684, -0.91113026, -0.91113026],
       [-0.41614684, -0.41614684, -0.41614684, -0.14550003]])

In [64]:
np.tan(arr1)

array([[-6.79971146, -0.29100619,  0.87144798, -0.14254654],
       [ 0.87144798, -2.18503986, -0.45231566, -0.45231566],
       [-2.18503986, -2.18503986, -2.18503986, -6.79971146]])

In [65]:
# numpy was created for mathematical operations 

In [66]:
np.tanh(arr1)

array([[0.99999977, 0.99998771, 0.99999834, 0.99505475],
       [0.99999834, 0.96402758, 0.99999997, 0.99999997],
       [0.96402758, 0.96402758, 0.96402758, 0.99999977]])

In [67]:
np.log10(arr1)

array([[0.90308999, 0.77815125, 0.84509804, 0.47712125],
       [0.84509804, 0.30103   , 0.95424251, 0.95424251],
       [0.30103   , 0.30103   , 0.30103   , 0.90308999]])

In [69]:
np.sqrt(arr1)

array([[2.82842712, 2.44948974, 2.64575131, 1.73205081],
       [2.64575131, 1.41421356, 3.        , 3.        ],
       [1.41421356, 1.41421356, 1.41421356, 2.82842712]])

In [70]:
np.power(arr1,2)

array([[64, 36, 49,  9],
       [49,  4, 81, 81],
       [ 4,  4,  4, 64]])

In [71]:
np.mean(arr1)

5.416666666666667

In [72]:
np.average(arr1)

5.416666666666667

In [74]:
np.median(arr1)

6.5

In [75]:
np.std(arr1)

2.8418988174966557

In [76]:
np.var(arr1)

8.07638888888889

In [77]:
np.min(arr1)

2

In [78]:
np.max(arr1)

9