In [146]:
# in colleges we use matlab, now python didn't have anything for numerical calculations , it was added by developers 

In [147]:
# numpy must be known , at any point of time you will pass file in numeric data

In [148]:
import numpy as np

In [149]:
l = [1,2,3,4] # list

In [150]:
np.array(l) # convert list to array, array is a another data type

array([1, 2, 3, 4])

In [151]:
ar = np.array(l)

In [152]:
ar

array([1, 2, 3, 4])

In [153]:
type(ar) # ndarray means n dimensional array

numpy.ndarray

In [154]:
 np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [155]:
# list can be converted into array -in many ways
np.asarray(l)

array([1, 2, 3, 4])

In [156]:
np.asanyarray(l)

array([1, 2, 3, 4])

In [157]:
a = [2,3,4]

In [158]:
np.asanyarray(a)

array([2, 3, 4])

In [159]:
b = np.matrix(l) # matrix is two dimensional # matrix is subclass of array, by default its 2 dimensional

In [160]:
b

matrix([[1, 2, 3, 4]])

In [161]:
np.asanyarray(b) # will not be converted to array, changes to any array form , because matrix is form of an array

matrix([[1, 2, 3, 4]])

In [162]:
a = np.array(l)

In [163]:
a

array([1, 2, 3, 4])

In [164]:
c = a

In [165]:
c

array([1, 2, 3, 4])

In [166]:
a

array([1, 2, 3, 4])

In [167]:
a == c

array([ True,  True,  True,  True])

In [168]:
c[0] = 1000

In [169]:
c

array([1000,    2,    3,    4])

In [170]:
a

array([1000,    2,    3,    4])

In [171]:
c

array([1000,    2,    3,    4])

In [172]:
# see we got 1000 at both in a and c , c points to same variable in numpy

In [173]:
d = np.copy(a)

In [174]:
d

array([1000,    2,    3,    4])

In [175]:
a

array([1000,    2,    3,    4])

In [176]:
d[0] = 600

In [177]:
d

array([600,   2,   3,   4])

In [178]:
a

array([1000,    2,    3,    4])

In [179]:
# see a didn't change incase of using a copy

In [180]:
# c = a is called shallow copy
# d = ... is called deep copy

In [181]:
# np has many functions to generate arrays 

In [182]:
# lets do that

In [183]:
np.fromfunction(lambda i,j : i==j,(3,3)) # function is used to tell it how to create data

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [184]:
# here it has to create 3, 3 matrix  but we have passed lambda function and there if i==j then it will show true

In [185]:
np.fromfunction(lambda i,j : i*j,(3,3)) 

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [186]:
np.fromfunction(lambda i,j : i*j,(3,2)) # 3 rows but only 2 columns

array([[0., 0.],
       [0., 1.],
       [0., 2.]])

In [187]:
iterable = (i*i for i in range(5)) # generator object


In [188]:
np.fromiter(iterable,float) # generate data from iterable variable , 2nd parameter is the what type of data you want 

array([ 0.,  1.,  4.,  9., 16.])

In [189]:
np.fromstring('234 234',sep=' ')

array([234., 234.])

In [190]:
# Data types in numpy

In [191]:
l = [2,3,4,5,6]

In [192]:
ar = np.array(l)

In [193]:
ar.ndim

1

In [194]:
ar2 = np.array([[1,2,3,4],[2,3,4,5]])

In [195]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [196]:
ar.ndim

1

In [197]:
ar2.ndim # ndim gives dimensions

2

In [198]:
ar.size # how many elements are there

5

In [199]:
ar2.size

8

In [200]:
ar.shape # one dim 

(5,)

In [201]:
ar2.shape # 2 rows and four columns 

(2, 4)

In [202]:
ar.dtype

dtype('int64')

In [203]:
ar2.dtype

dtype('int64')

In [204]:
ar22 = np.array([(1.4,45,45),(23,45,66)])

In [205]:
ar22

array([[ 1.4, 45. , 45. ],
       [23. , 45. , 66. ]])

In [206]:
ar22.dtype

dtype('float64')

In [207]:
range(5)

range(0, 5)

In [208]:
list(range(5))

[0, 1, 2, 3, 4]

In [209]:
# can range produce floating point data, with range function, can it take jump parameter as floating point

In [210]:
# no it does not allow float values 

In [211]:
# numpy has provision avail

In [212]:
np.arange(2.3,5.6) # jump is 1

array([2.3, 3.3, 4.3, 5.3])

In [213]:
np.arange(2.3,5.6,0.3)

array([2.3, 2.6, 2.9, 3.2, 3.5, 3.8, 4.1, 4.4, 4.7, 5. , 5.3])

In [214]:
list(np.arange(2.3,5.6,0.3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [215]:
np.linspace(1,5,10) #  will produce 10  data in between 1,5 scale , in between interval generates data

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [216]:
# we have logspace also

In [218]:
np.zeros(5) # produces array of 1 dim with all 0

array([0., 0., 0., 0., 0.])

In [220]:
np.zeros((3,4)) # 2 dim

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [223]:
np.zeros((3,4,2)) # 2 dim

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [224]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [226]:
ar4 = np.zeros((2,3,4,2))

In [227]:
ar4

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [229]:
np.ones(4)

array([1., 1., 1., 1.])

In [230]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [231]:
np.ones((2,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [232]:
on = np.ones((2,32))

In [233]:
on + 5

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.,
        6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]])

In [236]:
np.empty(4)

array([1., 1., 1., 1.])

In [238]:
np.empty((3,5)) # empty array values are there but they are negligable

array([[4.68112222e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000, 6.32404027e-322]])

In [240]:
np.eye(4) # identity matrices

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [244]:
np.linspace(2,4,20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [245]:
np.logspace(2,5,10)

array([   100.        ,    215.443469  ,    464.15888336,   1000.        ,
         2154.43469003,   4641.58883361,  10000.        ,  21544.34690032,
        46415.88833613, 100000.        ])

In [248]:
np.logspace(2,5,10,base=2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [249]:
# FAMOUS FUNCTIONS - random function

In [250]:
np.random.randn(3,4) # produce random data

array([[ 0.95026578,  0.72040259,  1.19605218,  1.39777446],
       [-1.18401974,  0.65215582,  0.40222974, -1.47934302],
       [-0.5792726 , -0.29135811, -0.34417059, -1.69385988]])

In [252]:
arr = np.random.randn(3,4)

In [255]:
import pandas as pd

In [256]:
pd.DataFrame(arr)

0         1         2         3
0  0.360026  0.117692 -0.664733  0.700913
1  1.297712  1.308980  1.699691  0.589608
2  0.251302 -1.844696  0.648369  0.275054

In [257]:
np.random.rand(3,4)

array([[0.75576328, 0.81692864, 0.17282359, 0.63988462],
       [0.63186493, 0.13482453, 0.4094236 , 0.15523625],
       [0.54548182, 0.38535406, 0.49505086, 0.95369982]])

In [258]:
# difference between randn and rand, randn -> mean = 0, sd = 1 where (standard normal distribution)
# rand 

In [260]:
np.random.randint(1,110,(3,4)) # 3 X 4 

array([[38, 68, 93, 51],
       [24, 80, 49, 90],
       [21, 92, 55, 26]])

In [261]:
pd.DataFrame(np.random.randint(1,110,(300,400)))

0    1    2    3    4    5    6    7    8    9    ...  390  391  392  \
0     24   75   92   73   68    9    4   18   41   24  ...   91  107   93   
1    103   54   46    3   94   25   40   72   90   19  ...   21    1   79   
2     59   13  101    7  104   13   62   16   63   47  ...   74   91   96   
3    106   49   73   16   25   98   43   10   81   64  ...   82   59   65   
4     42   38   10   38   45   80   32   23   65    5  ...   36   61  101   
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
295   13   68   76   90    8   84   20   54   90   75  ...   88   35   80   
296   45   86  105   30   58   29   75   81   76   25  ...  103  107   84   
297   27   21   45   21   55   76  108   74   33   15  ...   28   48   37   
298   37   72   96   85   17   60   10   63   82   57  ...   33   87   19   
299   70   41  106   49   30   47   22   89    7  107  ...   59   32    7   

     393  394  395  396  397  398  399  
0     44   33   72    6   71   52   47  
1     77   99   19   93   11   14   45  
2      5   13  105    5   77   63   99  
3     66  104   61  108  105   11   19  
4     93   42  103   95   86   44  101  
..   ...  ...  ...  ...  ...  ...  ...  
295  107   65   47  108   61   42  106  
296   53   86   65   17   80   44   23  
297   74   67   31   66   31   49    9  
298   92   76   75    4   50  101   83  
299   43   77   34   48   53  105   60  

[300 rows x 400 columns]

In [262]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test.csv')

In [263]:
arr = np.random.rand(3,4)

In [264]:
# changing the shape of data

In [265]:
arr

array([[0.59013655, 0.88222949, 0.68925471, 0.61267638],
       [0.84349754, 0.10041875, 0.35888721, 0.44860884],
       [0.64758603, 0.6648219 , 0.03130077, 0.16701943]])

In [267]:
arr.reshape(6,2) # rearranges matrix

array([[0.59013655, 0.88222949],
       [0.68925471, 0.61267638],
       [0.84349754, 0.10041875],
       [0.35888721, 0.44860884],
       [0.64758603, 0.6648219 ],
       [0.03130077, 0.16701943]])

In [268]:
arr.reshape(6,-1)

array([[0.59013655, 0.88222949],
       [0.68925471, 0.61267638],
       [0.84349754, 0.10041875],
       [0.35888721, 0.44860884],
       [0.64758603, 0.6648219 ],
       [0.03130077, 0.16701943]])

In [271]:
arr.reshape(6,-9)

array([[0.59013655, 0.88222949],
       [0.68925471, 0.61267638],
       [0.84349754, 0.10041875],
       [0.35888721, 0.44860884],
       [0.64758603, 0.6648219 ],
       [0.03130077, 0.16701943]])

In [272]:
# reshape is used heavily

In [273]:
arr1 = arr.reshape(6,-13243)

In [274]:
arr1

array([[0.59013655, 0.88222949],
       [0.68925471, 0.61267638],
       [0.84349754, 0.10041875],
       [0.35888721, 0.44860884],
       [0.64758603, 0.6648219 ],
       [0.03130077, 0.16701943]])

In [275]:
# taking out data from array

In [276]:
arr1[1][1]

0.6126763840028931

In [277]:
arr1[2:5]

array([[0.84349754, 0.10041875],
       [0.35888721, 0.44860884],
       [0.64758603, 0.6648219 ]])

In [279]:
arr1[2:5,1]

array([0.10041875, 0.44860884, 0.6648219 ])

In [282]:
arr = np.random.randint(1,100,(5,5))

In [283]:
arr > 50

array([[False, False,  True,  True, False],
       [ True,  True, False, False, False],
       [False, False, False,  True,  True],
       [ True, False, False, False, False],
       [False,  True, False,  True,  True]])

In [284]:
arr[arr>50]

array([70, 79, 98, 74, 92, 64, 63, 58, 78, 95])

In [285]:
arr # taking out array from array

array([[26, 21, 70, 79, 22],
       [98, 74, 42, 31, 46],
       [40, 43,  3, 92, 64],
       [63,  4, 11, 44, 34],
       [44, 58,  2, 78, 95]])

In [289]:
arr[2:4,[1,2]]

array([[43,  3],
       [ 4, 11]])

In [290]:
arr[0][0] = 2000

In [291]:
arr

array([[2000,   21,   70,   79,   22],
       [  98,   74,   42,   31,   46],
       [  40,   43,    3,   92,   64],
       [  63,    4,   11,   44,   34],
       [  44,   58,    2,   78,   95]])

In [292]:
# inbuilt funtions 

In [293]:
arr1 = np.random.randint(1,3,(3,3))

In [294]:
arr2 = np.random.randint(1,3,(3,3))

In [295]:
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [1, 1, 2]])

In [296]:
arr2

array([[1, 2, 1],
       [2, 2, 1],
       [2, 2, 1]])

In [298]:
arr1 + arr2 # index to index mapping is done here

array([[2, 3, 2],
       [3, 3, 3],
       [3, 3, 3]])

In [299]:
arr1/arr2

array([[1. , 0.5, 1. ],
       [0.5, 0.5, 2. ],
       [0.5, 0.5, 2. ]])

In [300]:
arr1 * arr2

array([[1, 2, 1],
       [2, 2, 2],
       [2, 2, 2]])

In [301]:
# matrix mult or normal multipulication # it is not matrix multipulication hwo do we do matrix multipulication

In [304]:
# two matrices can be multiplied only if n == p , column of first matrix should be equal to row of first matrix 

In [306]:
arr1 @ arr2 # @ will give you matrix multipulication

array([[5, 6, 3],
       [7, 8, 4],
       [7, 8, 4]])

In [308]:
arr1/0 # if done in python , but in  numpy then we get Inf

/tmp/ipykernel_1203/3832565204.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0 # if done in python , but in  numpy then we get Inf


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [309]:
arr1 + 100 # every number will be updated to 100

array([[101, 101, 101],
       [101, 101, 102],
       [101, 101, 102]])

In [310]:
arr1

array([[1, 1, 1],
       [1, 1, 2],
       [1, 1, 2]])

In [311]:
arr1 **2

array([[1, 1, 1],
       [1, 1, 4],
       [1, 1, 4]])

In [317]:
# Numpy - Broadcasting
arr = np.zeros((4,4))

In [318]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [319]:
row = np.array([1,2,3,4])

In [320]:
arr + row 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [321]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [322]:
row

array([1, 2, 3, 4])

In [323]:
#row by row addition - called broadcasting

In [325]:
row.shape

(4,)

In [327]:
row.T

array([1, 2, 3, 4])

In [328]:
# transpose of array


In [330]:
col = np.array([[1,2,3,4]])

In [331]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [332]:
col.T + arr

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [333]:
# column wise broadcasting  -> + 1 value acrossing a whole set

In [336]:
arr1 = np.random.randint(1,4,(3,4))

In [337]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 1.        , 1.73205081],
       [1.41421356, 1.        , 1.73205081, 1.        ],
       [1.        , 1.41421356, 1.73205081, 1.73205081]])

In [338]:
np.exp(arr1)

array([[ 2.71828183, 20.08553692,  2.71828183, 20.08553692],
       [ 7.3890561 ,  2.71828183, 20.08553692,  2.71828183],
       [ 2.71828183,  7.3890561 , 20.08553692, 20.08553692]])

In [339]:
np.log10(arr1)

array([[0.        , 0.47712125, 0.        , 0.47712125],
       [0.30103   , 0.        , 0.47712125, 0.        ],
       [0.        , 0.30103   , 0.47712125, 0.47712125]])

In [340]:
# how many things came in your minde are avail in numpy