In [16]:
# Sort, Search & Counting Funtions


In [17]:
import numpy as np  # note install numpy before importing 

In [18]:
arr = np.array([4,3,4,5,6,72,3,3,455,5,6,6])

In [19]:
np.sort(arr)

array([  3,   3,   3,   4,   4,   5,   5,   6,   6,   6,  72, 455])

In [20]:
np.searchsorted(arr,34) # where will you place this data 

12

In [21]:
arr1 = np.array([0,345,454,0,0,0,0])

In [22]:
# non- zero data

In [23]:
np.count_nonzero(arr1)

2

In [24]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [25]:
# filtering data

In [26]:
np.where(arr > 6)

(array([5, 8]),)

In [30]:
# np.extract(arr > 6)
np.extract(arr>3,arr) 

array([  4,   4,   5,   6,  72, 455,   5,   6,   6])

In [31]:
# byte swapping, repr data in bytes

In [33]:
arr.byteswap() # byte repr of data

array([  288230376151711744,   216172782113783808,   288230376151711744,
         360287970189639680,   432345564227567616,  5188146770730811392,
         216172782113783808,   216172782113783808, -4107001385185181696,
         360287970189639680,   432345564227567616,   432345564227567616])

In [34]:
# Numpy - Copies & Views

In [35]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [36]:
a = np.copy(arr) # deep copy

In [37]:
# chaning in a will not affect in original arr

In [43]:
b = arr.view() # equivalent to b = arr 

In [39]:
arr

array([  4,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [40]:
b[0] = 67

In [41]:
arr

array([ 67,   3,   4,   5,   6,  72,   3,   3, 455,   5,   6,   6])

In [42]:
# view is equivalent to shallow copy

In [44]:
# np has matrix library

In [45]:
import numpy.matlib as nm

In [46]:
# matrix library

In [48]:
nm.zeros(5) # in numpy it generated array, but here its matrix

matrix([[0., 0., 0., 0., 0.]])

In [49]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [51]:
nm.eye(5) # identity matrix 

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [52]:
# numpy linear algebra

In [53]:
arr1 = np.random.randint([[2,3],[4,5]])
arr2 = np.random.randint([[5,3],[2,5]])

In [54]:
np.dot(arr1,arr2) # matrix multipulicatin 

array([[0, 0],
       [4, 4]])

In [56]:
arr1@arr2 # also matrix multipulication

array([[0, 0],
       [4, 4]])

In [57]:
arr1

array([[0, 0],
       [2, 0]])

In [58]:
arr2

array([[2, 2],
       [1, 2]])